// Generated by CoffeeScript 1.6.3
(function() {
  var Renderer, coffeescript, config, div, _, __helper,
    __slice = [].slice;

  _ = require('underscore');

  config = require('./config');

  coffeescript = require('coffee-script');

  __helper = {
    entityMap: {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': '&quot;',
      "'": '&#39;',
      "/": '&#x2F;'
    },
    escapeHTML: function(content) {
      return content.toString().replace(/[&<>"'\/]/g, function(s) {
        return __helper.entityMap[s];
      });
    },
    isSelfCloseTag: function(tagName) {
      return false;
    },
    seekRenderer: function(args) {
      var caller;
      caller = args.callee;
      while (caller.renderer == null) {
        caller = caller.caller;
      }
      return caller.renderer;
    },
    renderTag: function() {
      var arg, args, attrs, contents, i, inline, renderer, tagName, _i, _len;
      tagName = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      renderer = __helper.seekRenderer(arguments);
      inline = contents = null;
      attrs = {
        classes: []
      };
      for (i = _i = 0, _len = args.length; _i < _len; i = ++_i) {
        arg = args[i];
        switch (false) {
          case !_.isFunction(arg):
            contents = arg;
            break;
          case !_.isObject(arg):
            _.extend(attrs, arg);
            break;
          case !(_.isString(arg) && args.length === 1):
            contents = arg;
            break;
          case !(_.isString(arg) && i === 0):
            inline = arg.replace(/(#|\.)([\w\d-]+)/gi, function(match, type, val) {
              if (type === '#') {
                if (attrs.id == null) {
                  attrs.id = val;
                }
              } else {
                attrs.classes.push(val);
              }
              return '';
            });
            break;
          default:
            contents = arg;
        }
      }
      return renderer._renderTag(tagName, attrs, inline, contents);
    }
  };

  div = function() {
    return __helper.renderTag.apply(null, ['div'].concat(Array.prototype.slice.call(arguments)));
  };

  Renderer = (function() {
    Renderer._renderId = 0;

    function Renderer(template, options) {
      var defineCommand, k, v;
      this.options = options;
      this.locals = _.extend({}, this.options.locals);
      if (_.keys(this.locals).length) {
        defineCommand = "var " + (_.keys(this.options.locals).join(',')) + ";";
        if (config.env.isNode != null) {
          require('vm').runInThisContext(defineCommand);
        } else {
          eval(defineCommand);
        }
        for (k in options) {
          v = options[k];
          eval("" + k + " = v;");
        }
      }
      eval("this.template = function() {" + template + "}");
      this.dataStack = [];
      this.sectionStack = [];
      this.extendStack = [];
    }

    Renderer.prototype.render = function(data, sections) {
      var htmlResult, previousRenderer, renderId;
      this.sections = sections != null ? sections : {};
      this.dataStack.push(this._patchData(data));
      renderId = "_render" + (Renderer.renderId++);
      this.sections[renderId] = [];
      this.sectionStack.push(renderId);
      this.extendStack.push([]);
      previousRenderer = this.template.renderer;
      this.template.renderer = this;
      this.template.apply(this._currentData(), []);
      htmlResult = this._generateResult(renderId);
      this.template.renderer = previousRenderer;
      delete this.sections[renderId];
      this.dataStack.pop();
      this.sectionStack.pop();
      this.extendStack.pop();
      return htmlResult;
    };

    Renderer.prototype._renderTag = function(tagName, attrs, inline, contents) {
      if (tagName === 'text') {
        return this._renderContent(contents, attrs.safe);
      }
      this._text("<", true);
      this._text("" + tagName);
      this._attrs(attrs);
      if (inline != null) {
        this._text("" + inline, attrs.safe);
      }
      if (__helper.isSelfCloseTag(tagName)) {
        if (contents != null) {
          contents = this._renderContent(contents, attrs.safe);
          if (contents != null) {
            this._attrs({
              value: contents
            });
          }
        }
        return this._text(' />', true);
      } else {
        this._text('>', true);
        this._renderContent(contents, attrs.safe);
        this._text('</', true);
        this._text(tagName);
        return this._text('>', true);
      }
    };

    Renderer.prototype._renderContent = function(contents, safe) {
      var previousRenderer, result;
      if (safe == null) {
        safe = false;
      }
      switch (false) {
        case !_.isFunction(contents):
          previousRenderer = contents.renderer;
          contents.renderer = this;
          result = contents.call(this.data);
          if (_.isString(result)) {
            this._text(result, safe);
          }
          contents.renderer = previousRenderer;
          return result;
        default:
          this._text(contents, safe);
          return contents;
      }
    };

    Renderer.prototype._attrs = function(attrs, safe) {
      var attr, attrReady, k, v, val, _results,
        _this = this;
      if (safe == null) {
        safe = false;
      }
      attrReady = function(key, val) {
        _this._text(" " + key + "=", safe);
        _this._text('"', true);
        _this._text(val, safe);
        return _this._text('"', true);
      };
      _results = [];
      for (attr in attrs) {
        val = attrs[attr];
        switch (false) {
          case val !== true:
            _results.push(attrReady(attr, attr));
            break;
          case !_.isFunction(val):
            _results.push(attrReady(attr, "(" + val + ").call(this);"));
            break;
          case attr !== 'data':
            _results.push((function() {
              var _results1;
              _results1 = [];
              for (k in val) {
                v = val[k];
                _results1.push(attrReady("data-" + k, v));
              }
              return _results1;
            })());
            break;
          case attr !== 'classes':
            if (val.length) {
              _results.push(attrReady('class', val.join(' ')));
            } else {
              _results.push(void 0);
            }
            break;
          case attr !== 'safe':
            break;
          default:
            _results.push(attrReady(attr, val));
        }
      }
      return _results;
    };

    Renderer.prototype._text = function(content, safe) {
      if (safe == null) {
        safe = false;
      }
      return this._currentSection().push(safe ? content.toString() : __helper.escapeHTML(content));
    };

    Renderer.prototype._generateResult = function(renderId) {
      return this.extendStack[this.extendStack.length - 1].join('') + _.flatten(this.sections[renderId]).join('');
    };

    Renderer.prototype._currentData = function() {
      return this.dataStack[this.dataStack.length - 1];
    };

    Renderer.prototype._currentSection = function() {
      return this.sections[this.sectionStack[this.sectionStack.length - 1]];
    };

    Renderer.prototype._patchData = function(data) {
      return _.extend(data, {
        env: _.pick(this.options, 'templatePath')
      });
    };

    return Renderer;

  })();

  module.exports = {
    compile: function(template, options) {
      var tpl;
      if (options == null) {
        options = {};
      }
      tpl = new Renderer(coffeescript.compile(template, {
        bare: true
      }), options);
      return function(data, sections) {
        if (data == null) {
          data = {};
        }
        if (sections == null) {
          sections = {};
        }
        return tpl.render(data, sections);
      };
    },
    compilePath: {}
  };

}).call(this);
