// Generated by CoffeeScript 1.6.3
(function() {
  var config, env;

  env = {
    isBrowser: typeof window !== "undefined" && window !== null,
    isNode: typeof process !== "undefined" && process !== null
  };

  module.exports = config = {
    env: env
  };

}).call(this);
