// Generated by CoffeeScript 1.6.3
(function() {
  var _,
    __slice = [].slice;

  _ = require('underscore');

  module.exports = {
    mergeElements: function() {
      var arg, args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return _.union(_.flatten((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = args.length; _i < _len; _i++) {
          arg = args[_i];
          _results.push(arg.split(' '));
        }
        return _results;
      })()));
    }
  };

}).call(this);
