// Generated by CoffeeScript 1.6.3
(function() {
  var config, fs, _,
    __slice = [].slice;

  _ = require('underscore');

  config = require('./config');

  fs = require('fs');

  module.exports = {
    mergeElements: function() {
      var arg, args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return _.union(_.flatten((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = args.length; _i < _len; _i++) {
          arg = args[_i];
          _results.push(arg.split(' '));
        }
        return _results;
      })()));
    },
    loadTemplateFromPath: function(path, cb) {
      var requirejs;
      path = "" + config.env.prefix + path + "." + config.env.extension;
      switch (false) {
        case !config.env.isNode:
          return fs.readFile(path, 'utf8', cb);
        case !config.env.isBrowser:
          requirejs = require('requirejs');
          return requirejs(["text!" + path], function(templateContent) {
            return cb(null, templateContent);
          });
        default:
          return cb('unknown working environment.');
      }
    },
    loadTemplateFromPathSync: function(path) {
      path = "" + config.env.prefix + path + "." + config.env.extension;
      if (config.env.isNode) {
        return fs.readFileSync(path, 'utf8');
      }
      throw new Error("Current running environment doesn't support sync mode.");
    }
  };

}).call(this);
